version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
  api:
    image: pedrogonic/dockerspringdemoimage
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dockertest
    ports:
      - 8090:8080
    links:
      - mongodb